version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: banking_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: banking
      MYSQL_USER: bankuser
      MYSQL_PASSWORD: bankpass
    volumes:
      - db_data:/var/lib/mysql
      - ./src/main/resources/db/migration:/flyway/sql:ro
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping","-h","localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data:
